repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
        files: \.(yml|yaml)$
      - id: check-json
        files: \.json$
  - repo: local
    hooks:
      - id: tomlcheck
        name: Check TOML Syntax
        description: Checks TOML files for valid syntax.
        entry: tomlcheck
        language: system
        files: \.toml$
        stages: [commit, push, manual]
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: system
        types: [python]
  - repo: local
    hooks:
      - id: flake8
        name: flake8
        entry: flake8
        language: system
        types: [python]
  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: isort
        language: system
        types: [python]
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: mypy
        language: python
        types: [python]
        exclude: tests
